### ISSUE TITLE
Práctica de Estimación de Costos

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/estimacion-de-costos-entrevista-gp#1]
[Estimación de costos (1).pdf](https://github.com/SistemasTecTlaxiaco/estimacion-de-costos-entrevista-gp/files/7571587/Estimacion.de.costos.1.pdf)

**Comment by Jaci14** [comment]
Realiza una buena investigacion de costos en cuanto recursos humanos y servicios requeridos, plantea adecuadamente su estimacion de costos y su preaupuesto final.

Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
